# Generated by Django 6.1 on 2026-08-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('classicauthor', '0002_classicauthor_genres'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literarywork_author', to='author.author', verbose_name='author')),
                ('classic_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literarywork_classicauthor', to='classicauthor.classicauthor', verbose_name='classic_author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literarywork_genre', to='genre.genre', verbose_name='genre')),
            ],
            options={
                'verbose_name': 'LiteraryWork',
                'verbose_name_plural': 'LiteraryWorks',
                'ordering': ['title'],
            },
        ),
    ]
