# Generated by Django 6.1 on 2026-08-31 16:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_literarywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='literarywork',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location'),
        ),
    ]
