# Generated by Django 6.1 on 2026-09-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_literarywork_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=4096, verbose_name='link')),
                ('literary_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_literarywork', to='author.literarywork', verbose_name='literary_work')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=4096, verbose_name='link')),
                ('literary_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_literarywork', to='author.literarywork', verbose_name='literary_work')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
