# Generated by Django 6.1 on 2026-09-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_imagen_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literarywork',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
