# Generated by Django 6.1 on 2026-09-03 13:28

import apps.author.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_literarywork_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='link',
        ),
        migrations.AddField(
            model_name='imagen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.author.utils.path_and_rename, verbose_name='Image'),
        ),
    ]
