# Generated by Django 6.1 on 2026-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_remove_imagen_link_imagen_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author_first_last_name'),
        ),
    ]
