# Generated by Django 6.1 on 2026-09-16 14:26

import apps.author.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_author_unique_author_first_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.author.utils.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), apps.author.utils.validate_image_max_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=4096, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='link'),
        ),
    ]
