"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').strip().lower() in ('true', '1', 'yes', 'on')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Sin esto, Django usa 'same-origin' por defecto y el navegador no envía
# Referer a orígenes externos (p.ej. tile.openstreetmap.org), que lo exige
# por política de uso y devuelve 403.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

DJANGO_SITE_HEADER_NAME = os.getenv('SITE_HEADER_NAME')
DJANGO_SITE_INDEX_TITLE = os.getenv('SITE_INDEX_TITLE')
DJANGO_SITE_TITLE = os.getenv('SITE_TITLE')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    #extension-gis.
    'django.contrib.gis',
    #extension-busqueda-sin-acentos/aproximada (unaccent/pg_trgm) en el admin.
    'django.contrib.postgres',
    #extension-mapa.
    'leaflet',
    #apps
    'apps.base',
    'apps.classicauthor',
    'apps.genre',
    'apps.author',
    #front
    'apps.front'
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE':os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Sustituye por completo el backend de usuario/contraseña de Django: el
# login del admin ya no comprueba la contraseña (ver
# apps.base.forms.OTPAdminAuthenticationForm), solo el código de un solo uso
# de apps.base.models.LoginCode (docs/DEUDA.md, 2026-09-15, OWASP A07).
AUTHENTICATION_BACKENDS = ['apps.base.auth_backends.OTPBackend']


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# "MAILERS" (config anterior) no es un setting que Django reconozca, nunca
# llegó a usarse (ver docs/DEUDA.md, 2026-09-15). En desarrollo (DEBUG=True)
# los códigos de acceso se imprimen por consola en vez de enviarse de
# verdad, para no depender de credenciales SMTP reales en el devcontainer.
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp-relay.brevo.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# --- Seguridad HTTPS ---
# nginx hace de proxy TLS delante de gunicorn en producción. Estos ajustes
# solo aplican cuando DEBUG=False: en el devcontainer (DEBUG=True, sin TLS
# delante) forzarlos rompería el entorno de desarrollo.
if not DEBUG:
    # Permite desactivar temporalmente la redirección durante el arranque en
    # frío de certbot (ver runbook de nginx/certbot), cuando nginx todavía
    # solo sirve HTTP porque no existe certificado. Por defecto activo.
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').strip().lower() in ('true', '1', 'yes', 'on')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Empezar con un valor bajo (1 día) y subirlo tras validar unos días que
    # todo funciona correctamente sobre HTTPS; SECURE_HSTS_PRELOAD es casi
    # irreversible una vez el dominio entra en la lista de precarga de los
    # navegadores, así que no activarlo hasta confirmar que el despliegue es
    # estable.
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 60 * 60 * 24))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False').strip().lower() in ('true', '1', 'yes', 'on')

    _domain = os.getenv('DOMAIN', '')
    CSRF_TRUSTED_ORIGINS = [f'https://{_domain}'] if _domain else []


# --- Logging ---
# Sin esto, en producción (DEBUG=False) Django no registra nada: el handler
# de consola del logging por defecto solo se activa con DEBUG=True, y el
# único handler activo en producción (mail_admins) no tiene a dónde enviar
# nada porque no hay ADMINS ni un EMAIL_BACKEND real configurados. Salida a
# stdout (no a fichero) para que la capture "docker logs ahtrcservice_container",
# ya con rotación vía Docker (json-file) configurada en docker-compose.prod.yml.
LOGGING = {
    'version': 1,
    # Necesario para no desactivar el logging por defecto de Django en
    # desarrollo (runserver deja de imprimir las peticiones sin esto).
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        # 4xx (WARNING) y 5xx con traceback (ERROR): Django ya los emite por
        # este logger de fábrica, solo hacía falta darle un handler activo.
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        # CSRF rechazado, Host no permitido, y los 403 del propio admin
        # (accesos denegados): también los emite Django de fábrica.
        'django.security': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}
