# Generated by Django 6.1 on 2026-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_unassigned',
            field=models.BooleanField(default=False, verbose_name='is_unassigned'),
        ),
    ]
