# Generated by Django 6.1 on 2026-09-17 11:33

from django.db import migrations


def set_unassigned_flag(apps, schema_editor):
    Genre = apps.get_model('genre', 'Genre')
    Genre.objects.filter(name='SIN ASIGNAR').update(is_unassigned=True)


def unset_unassigned_flag(apps, schema_editor):
    Genre = apps.get_model('genre', 'Genre')
    Genre.objects.filter(name='SIN ASIGNAR').update(is_unassigned=False)


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_genre_is_unassigned'),
    ]

    operations = [
        migrations.RunPython(set_unassigned_flag, unset_unassigned_flag),
    ]
