# Generated by Django 6.1 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicauthor', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicauthor',
            name='genres',
            field=models.ManyToManyField(to='genre.genre'),
        ),
    ]
