# Generated by Django 6.1 on 2026-09-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicauthor', '0002_classicauthor_genres'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicauthor',
            name='genres',
            field=models.ManyToManyField(to='genre.genre', verbose_name='genres'),
        ),
    ]
