# Generated by Django 6.1 on 2026-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicauthor', '0003_alter_classicauthor_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicauthor',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
    ]
