# Generated by Django 6.1 on 2026-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicauthor', '0004_alter_classicauthor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicauthor',
            name='is_unassigned',
            field=models.BooleanField(default=False, verbose_name='is_unassigned'),
        ),
    ]
