# Generated by Django 6.1 on 2026-09-17 11:33

from django.db import migrations


def set_unassigned_flag(apps, schema_editor):
    ClassicAuthor = apps.get_model('classicauthor', 'ClassicAuthor')
    ClassicAuthor.objects.filter(name='SIN ASIGNAR').update(is_unassigned=True)


def unset_unassigned_flag(apps, schema_editor):
    ClassicAuthor = apps.get_model('classicauthor', 'ClassicAuthor')
    ClassicAuthor.objects.filter(name='SIN ASIGNAR').update(is_unassigned=False)


class Migration(migrations.Migration):

    dependencies = [
        ('classicauthor', '0005_classicauthor_is_unassigned'),
    ]

    operations = [
        migrations.RunPython(set_unassigned_flag, unset_unassigned_flag),
    ]
