# Generated by Django 6.1 on 2026-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='is_open')),
            ],
            options={
                'verbose_name': 'MapConfig',
                'verbose_name_plural': 'MapConfig',
            },
        ),
    ]
