# Generated by Django 6.1 on 2026-09-17 15:09

from django.db import migrations


def create_singleton(apps, schema_editor):
    MapConfig = apps.get_model('front', 'MapConfig')
    MapConfig.objects.get_or_create(pk=1, defaults={'is_open': False})


def remove_singleton(apps, schema_editor):
    MapConfig = apps.get_model('front', 'MapConfig')
    MapConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_singleton, remove_singleton),
    ]
